
[platformio]
default_envs = cane

[env:cane]
platform = espressif32
board = lolin32_lite
framework = arduino
lib_deps =
	stm32duino/STM32duino ISM330DLC@^2.0.1
	arduino-libraries/Arduino_Modulino @ ^0.7.0
build_src_filter = -<**/*.cpp> +<cane/**/*.cpp> +<*.h>

[env:distance_test]
platform = espressif32
board = lolin32_lite
framework = arduino
lib_deps =
	arduino-libraries/Arduino_Modulino @ ^0.7.0
build_src_filter = -<**/*.cpp> +<distance_test/**/*.cpp> +<*.h>
